### PR TITLE
PP-556: Display audio book durations in book detail pages

### PR DESCRIPTION
**Pull request by io7m**
**What's this do?**
Adds audio book durations to book detail pages, if available.

**Why are we doing this? (w/ JIRA link if applicable)**
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-556

**How should this be tested? / Do these changes have associated tests?**
Check that books in the Minotaur Palace Bookshelf feed have durations. Not all books have them. One that does is "Good Omens".

**Dependencies for merging? Releasing to production?**
None.

**Have you updated the changelog?**
Yes.

**Has the application documentation been updated for these changes?**
N/A

**Did someone actually run this code to verify it works?**
@io7m Tried it.
Screenshot_20231113_134347

### CODE REVIEW

**Review by nunommts — CHANGES_REQUESTED** [review]
This looks good and it's working, but I have two notes:

1 - The card says `the duration should be displayed using this format: “Duration: X hours, Y minutes”. For example: “Duration: 13 hours, 6 minutes”` and you defined it as "Minutes, Seconds"
2 - I haven't seen the layouts but should the "Duration" field go to the bottom of the container? I think it's somehow relevant and as a user I'd expect to see it a bit above on the list.

**Comment by io7m** [comment]
> 1 - The card says `the duration should be displayed using this format: “Duration: X hours, Y minutes”. For example: “Duration: 13 hours, 6 minutes”` and you defined it as "Minutes, Seconds" 

Wow, I have no idea how I managed that.

> 2 - I haven't seen the layouts but should the "Duration" field go to the bottom of the container? I think it's somehow relevant and as a user I'd expect to see it a bit above on the list.

The ticket didn't specify.

**Comment by io7m** [comment]
:sweat_smile: 

Screenshot_20231113_141854

**Comment by nunommts** [comment]
@io7m Got it! I'll approve this now and we can see if someone agrees with me in the future 😄

**Review by nunommts — APPROVED** [review]

**Comment by io7m** [comment]
:rocket:

**Pull request merged**
