### PR TITLE
Removed profile idle timer

### PR DESCRIPTION
**Pull request by nunommts**
**What's this do?**
This PR removes the profile idle timer related code and logic from the app.

**Why are we doing this? (w/ JIRA link if applicable)**
There's a [task](https://ebce-lyrasis.atlassian.net/browse/PP-255) to remove this as it's no longer needed.

**How should this be tested? / Do these changes have associated tests?**
I'm not sure how to test this

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

### CODE REVIEW

**Comment by io7m** [comment]
The changes seem fine. I'm not entirely clear on why the tests are failing.

**Comment by io7m** [comment]
Looks like it might be my "Reduce logging volume" commit that broke them.

**Comment by nunommts** [comment]
@io7m I'm not sure either. The tests have been failing since [this action](https://github.com/ThePalaceProject/android-core/actions/runs/6825851934) and I don't know why

**Comment by io7m** [comment]
They fail locally. I'm working on it now.

**Review by io7m — APPROVED** [review]
Glad to see this ancient and useless code go away.

**Pull request merged**
