### PR TITLE
Updated buttons layout

### PR DESCRIPTION
**Pull request by nunommts**
Removed one of the two empty spaces in order for the download button have more width and don't crop it's text

### CODE REVIEW

**Comment by io7m** [comment]
Looks good! I'm amused that this is all it took.

**Review by io7m — APPROVED** [review]

**Review by ray-lee — APPROVED** [review]
LGTM. Thanks!

**Comment by ray-lee** [comment]
@nunommts In the future, please fill out the pull request template that appears when you make the PR in GitHub. That will ensure that we have a record of the full context for a change, and have a link to the ticket, etc. Have a look at the closed PRs for examples.

**Comment by nunommts** [comment]
> @nunommts In the future, please fill out the pull request template that appears when you make the PR in GitHub. That will ensure that we have a record of the full context for a change, and have a link to the ticket, etc. Have a look at the closed PRs for examples.

Sure! I'm sorry about that

**Pull request merged**
