### PR TITLE
Added audiobook player commands

### PR DESCRIPTION
**Pull request by nunommts**
**NOTE** This PR can only be merged after [this PR in the Audiobook module](https://github.com/ThePalaceProject/android-audiobook/pull/11) is merged

**What's this do?**
This PR updates the AudioBookActivity to implement the two new methods that were added to the PlayerFragmentListenerType interface from the Audiobook module. These two methods return an image to display as the small icon of the notification and the book cover image, needed by the Audiobook service that controls the Audiobook player.

**Why are we doing this? (w/ JIRA link if applicable)**
There's [a request](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=c5596de5b57d4027bf2984acfa70f930&p=36be29dc34ce499a93cd28ac0896ea1c) to add this feature to be similar to the iOS version and to provide the user an opportunity of pausing or resuming the book player directly from the lock screen instead of having to unlock the screen and reopen the app.

**How should this be tested? / Do these changes have associated tests?**

Open the app
Open any audiobook
Drag down the status bar and verify that [a notification has been created](https://user-images.githubusercontent.com/79104027/146064860-4f562560-c711-4d8e-8ef6-84f28f407bb1.png)
 with the book info
Turn off the screen
Turn on the screen and [check the notification is visible](https://user-images.githubusercontent.com/79104027/146064908-4256b10f-d176-4a40-aa79-bdf0edc01566.png)
Press pause/play and verify the player pauses and resumes

**Dependencies for merging? Releasing to production?**
None

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Tested by @nunommts

### CODE REVIEW

**Comment by ray-lee** [comment]
@nunommts Do you have an update to android-platform that hasn't been pushed? The build is failing because it can't find the commit that is now referenced.

**Comment by nunommts** [comment]
@ray-lee I did update the audiobook version. Has the PR been merged yet?

**Comment by ray-lee** [comment]
@nunommts Yes, the audiobook PR has been merged.

**Comment by nunommts** [comment]
@ray-lee ok, so I must have done something wrong while committing and pushing the new version. I'll recheck that first thing in the morning

**Comment by nunommts** [comment]
@ray-lee It looks fine now :)

**Review by ray-lee — COMMENTED** [review]
Where does main_icon.png get displayed? That one is a demo image for the vanilla app that we probably shouldn't use in the Palace app.

**Comment by nunommts** [comment]
@ray-lee It's displayed as the notification icon in the status bar. I copied it from the `simplified-main` module -> `MainNotificationResources.kt` since it was being used for the same purpose. But I can update it, though. What image do you think we should use?

**Comment by ray-lee** [comment]
@nunommts This might be something different with Android 12, but I'm not seeing the same thing on the lock screen as you. I can't control playback without unlocking the phone. Here's what I see:



If I tap on the row that has the little Palace icon, it makes me unlock the phone, then I can access the controls.

I have apps that allow you to control playback without unlocking, like Stitcher:



Maybe something needs to be done differently on Android 12?

**Comment by ray-lee** [comment]
@nunommts I'm seeing the Palace icon in the status bar, which I think is the right thing. Do you see the picture of books? Maybe it depends on the Android version?

**Comment by ray-lee** [comment]
More information: If the Palace app is the only one showing a notification, then I see the controls and can use them without unlocking. But if there are any other notifications, then the Palace notification gets collapsed into that bar, and I can only get to the controls by unlocking the phone. There might be something that other apps are doing to make sure their notification is always showing.

**Comment by nunommts** [comment]
@ray-lee Nice catches! I'll investigate and test with an Android 12 device

**Comment by nunommts** [comment]
@ray-lee Now the Audiobook PR is merged, I think you can merge this one as well.

**Review by ray-lee — APPROVED** [review]

**Pull request merged**
