### PR TITLE
Added book loan duration to buttons

### PR DESCRIPTION
**Pull request by nunommts**
[fix] Increased buttons container height on dimensions.xml
[new] Added clock icon
[upd] Updated method that returns the missing loan days/weeks/months/etc.
[new] Created helper method to return the string value of the loan duration
[new] Added methods to create a ViewGroup with the loan duration and the button text

**What's this do?**
This PR creates methods to display the buttons to "Download" and "Read" with the information of how many days/weeks/months/etc. the loan lasts.
In order to do so, this PR updates one existing method to compare the current time with the loan end time and then it shows the according value in the according unit (there are some conditions to display "y", "m", "w" that were obtained from the iOS app). To avoid text from being cropped, this PR also has a minor change in the height of the buttons container.

**Why are we doing this? (w/ JIRA link if applicable)**
There was a request made to display the missing time on a book loan like it's in the iOS app. The ticket can be found here: [https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=32b300218b974ecdb2054533a8b4a6d2&p=308a84629c7b400fb716df8c83af0f3b](url)

**How should this be tested? / Do these changes have associated tests?**
1 - Choose LYRASIS library (this library has a lot of books with loan duration)
2 - Get a book (**Companions** from Christina Hesselholdt or **Phoenix Rising** from Keith Nightingale, for example)
3 - Go to the "Books" tab and see if the book has a duration right before the "Read" or "Download" text in the button

**Dependencies for merging? Releasing to production?**
None

**Has the application documentation been updated for these changes?**
None

**Did someone actually run this code to verify it works?**
Tested by @nunommts

### CODE REVIEW

**Review by ray-lee — CHANGES_REQUESTED** [review]
@nunommts, it looks like you need to fix some lint errors. Look at the results of the PR build (under Actions, and also linked from the failing check message on the PR). You can also run `gradlew ktlint` to run the linter locally.

A couple nits about the PR itself:
- The link to the Notion ticket isn't appearing.
- The title of the PR doesn't really describe what it does. GitHub defaults it to the first commit message, but that's usually not great. For this, something like "Show remaining loan duration on Download and Read buttons" would be appropriate. This helps people quickly see what has been done when looking at the lists of open/closed PRs. The PR title is also used as the commit message when we do a squash merge. If I do the merge, I'll edit the commit message if it's not clear, but it's helpful if it's already clear.

I'll look at the code tomorrow.

Thanks!

**Comment by io7m** [comment]
`./gradlew ktlintFormat` can be used to correct style-related issues. It won't be able to fix things like star imports, sadly.

**Comment by nunommts** [comment]
@ray-lee Thank you for your feedback! I saw it failed after running the pipeline but I had my laptop turned off so it had to wait :D
I fixed the title like you suggested and also applied some changes to the code

**Review by ray-lee — COMMENTED** [review]
Thanks for those changes, @nunommts. I'm noticing some functional issues when I run this. I'll discuss with you on slack.

**Review by ray-lee — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
