### PR TITLE
Use ThePalaceProject fork of the Readium 2 component.

### PR DESCRIPTION
**Pull request by ray-lee**
**What's this do?**

Use our fork of the R2 navigator component.

**Why are we doing this? (w/ JIRA link if applicable)**

This allows us to add bug fixes and features to R2 that are not in the NYPL repo. Currently, this is needed for changes for Adobe certification.

Notion: https://www.notion.so/lyrasis/Font-size-button-Android-f49da8f869b84d1c80755c6c0e8c4937

**How should this be tested? / Do these changes have associated tests?**

Read a book. Open the settings dialog, and tap the default text size button. Tap the decrease text size button repeatedly. After three size reductions, the button should become disabled. Tap the default text size button. Tap the increase text size button. After 28 size increases, the button should become disabled.

**Dependencies for merging? Releasing to production?**

This PR should be merged first: https://github.com/ThePalaceProject/android-r2/pull/1

**Has the application documentation been updated for these changes?**

n/a

**Did someone actually run this code to verify it works?**

@ray-lee ran the Palace app.

### CODE REVIEW

**Comment by io7m** [comment]
This is needed for the neutral colour scheme too.

**Review by io7m — APPROVED** [review]
:+1:

**Comment by io7m** [comment]
I take it you didn't run into any problems with publishing?

**Comment by ray-lee** [comment]
Publishing seemed to work fine, at least for snapshots.

**Pull request merged**
